# Generated by Django 5.0 on 2024-03-03 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="cart_id",
            new_name="cart",
        ),
    ]
