# Generated by Django 5.0 on 2024-03-07 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_order_orderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="cart",
            new_name="order",
        ),
    ]
